
###Ping

GET http://localhost:3000/api/ping

###SIGN
POST http://localhost:3000/api/auth/sign
Content-Type: application/json

{
    "name":"ddvdvd",
    "email":"niccssd@gmail.com",
    "username":"ccdcnis"
}

### login

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "magicUrl":"cf971d00-afed-4d3b-9f48-2c910f5920ae" }
    