
###Ping

GET http://localhost:5000/api/ping

###SIGN
POST http://localhost:5000/api/auth/sign
Content-Type: application/json

{
    "name":"nisssnif",
    "email":"niccdsscf@gmail.com",
    "username":"ccdccnis"
}

### login

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "magicUrl":"db00d8f7-f8c8-4366-be40-45d22db5074b"    }
    