
###Ping

GET http://localhost:3000/api/ping

###SIGN
POST http://localhost:3000/api/auth/sign
Content-Type: application/json

{
    "name":"ddvdd",
    "email":"ivddv@gmail.com",
    "username":"dcvds"
}

### login

POST http://localhost:3000/api/auth/login
Content-Type: application/json


{
  "magicUrl": "17835616-4955-4fc6-b804-e347d0e84f59"
}